version: '3'
services:
    web-server:
        build:
           context: web-server
        container_name: web-server
        environment:
            TZ: Asia/Tokyo
        tty: true
        volumes:
            - ./web-server/src/:/usr/src/app
        ports:
      ports:
           - 9051:9050
    express:
        build:
           context: express
        environment:
            TZ: Asia/Tokyo
        tty: true
        volumes:
            - ./express/src/:/usr/src/app
        ports:
             - 8081:8080

    mongo:
        image: mongo
        restart: always
        environment:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: root
          MONGO_INITDB_DATABASE: my-smart-room
        ports:
          - 27017:27017
        volumes:
          - ./mongo/db:/data/db
          - ./mongo/configdb:/data/configdb
          - ./mongo/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
  
    mongo-express:
        image: mongo-express
        restart: always
        ports:
          - 18081:8081
        environment:
          ME_CONFIG_MONGODB_ADMINUSERNAME: root
          ME_CONFIG_MONGODB_ADMINPASSWORD: root
          ME_CONFIG_MONGODB_PORT: 27017
        depends_on:
          - mongo

