version: '3'
services:
    web-server:
        build:
           context: web-server
        container_name: web-server
        environment:
            TZ: Asia/Tokyo
        tty: true
        volumes:
            - ./web-server/src/:/usr/src/app
        ports:
             - 8081:8080

    mongo:
        image: mongo
        restart: always
        environment:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: root
        ports:
          - 27017:27017
        volumes:
          - ./db:/data/db
          - ./configdb:/data/configdb
  
    mongo-express:
        image: mongo-express
        restart: always
        ports:
          - 18081:8081
        environment:
          ME_CONFIG_MONGODB_ADMINUSERNAME: root
          ME_CONFIG_MONGODB_ADMINPASSWORD: root


